name: Metrics

on:
  schedule:
    - cron: "0 * * * *"   # runs hourly
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          output_action: none   # ‚ùó no commits, no repo writes

          # Base config
          user: prashantucer
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Calcutta

          # Chess TEMP OFF
          # plugin_chess: yes
          # plugin_chess_platform: lichess.org
          # plugin_chess_user: A_XEVIL_WRATH_PP
          # plugin_chess_token: ${{ secrets.CHESS_TOKEN }}
          # plugin_chess_animation: '{"size":40,"delay":3,"duration":0.6}'

          # Plugins
          plugin_fortune: yes

          plugin_introduction: yes
          plugin_introduction_title: yes

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_threshold: "0%"

          plugin_leetcode: yes
          plugin_leetcode_user: prashantucer
          plugin_leetcode_sections: solved
          plugin_leetcode_limit_recent: 2

          plugin_people: yes
          plugin_people_limit: 10
          plugin_people_size: 25
          plugin_people_types: followers, following

          plugin_stars: yes
          plugin_stars_limit: 4

          # Footer OFF
          config_display_footer: no
